# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlowControllersExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlowControllersExample
  pod 'Alamofire', '~> 4.6'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'SwiftGen'
end
